name: AmazingBoard
author: RicoBytes
version: 0.3
main: it.urial.ricobytes.home.AmazingBoard
softdepend: [PlaceholderAPI]

commands:
    amazingboard:
        usage: /<command>
        description: Admin command of AmazingBoard
    ab:
        usage: /<command>
        description: Admin command of AmazingBoard